### ISSUE TITLE
SensorControl cannot find blhost.exe

### ISSUE THREAD

**Issue by rdpoor** [rdpoor/cp#38]
In SensorControl v1.2:
```
Update Firmware (Type Ctrl-C to return to main menu)
===============
Enter firmware image name[cp-crc.srec]: c:\users\engineer\utility\cp-crc.srec
Restarting Instrument 2/2 seconds
Entering Bootloader 2.0/2.0 seconds
###### establish communication with bootloader
Traceback (most recent call last):
  File "SensorControl.py", line 26, in <module>
    main()
  File "SensorControl.py", line 22, in main
    command_processor.process_loop()
  File "C:\Users\engineer\utility\command_processor.py", line 150, in process_loop
    self.process()
  File "C:\Users\engineer\utility\command_processor.py", line 176, in process
    self.process_command(matched)
  File "C:\Users\engineer\utility\command_processor.py", line 183, in process_command
    c.fn()
  File "C:\Users\engineer\utility\command_processor.py", line 865, in cmd_update_firmware
    self.update_firmware(filename)
  File "C:\Users\engineer\utility\command_processor.py", line 1074, in update_firmware
    ['get-property', '12'])
  File "C:\Users\engineer\utility\command_processor.py", line 1061, in tell_blhost
    subprocess.run(bl_cmd)
  File "C:\Users\engineer\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\engineer\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\engineer\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by rdpoor** [comment]
Fixed in https://github.com/rdpoor/cp/commit/66f5c08756787072b60193b7bf7b470627ab7ea8
